# Expose the app on EC2 port 30080.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort

  # Send requests to pods with these matching labels.
  selector:
    app.kubernetes.io/name: panel-ai
    app.kubernetes.io/instance: {{ .Release.Name }}

  # EC2 port 30080 forwards through the Service to app port 3000.
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
